steps:
# Kaniko cache (optmisation)
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --cache=true
  - --cache-ttl=12h

# Install
- name: 'node:12.16.3'
  entrypoint: npm
  args: [ 'install' ]

# Inject config
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - 'gcloud secrets versions access latest --project=$PROJECT_ID --secret=firebase-config > config.js'

# Build
- name: 'node:12.16.3'
  entrypoint: npm
  args: [ 'run', 'build' ]

# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: [ 'deploy', '--project=$PROJECT_ID', '--only=hosting' ]
